# ワークフローの名前
name: Post Daily Tweet

# 実行のきっかけを設定
on:
  schedule:
    # 日本時間の午前7時 (前日の22時UTC) に実行
    - cron: '0 22 * * *'
    # 日本時間の午後5時 (同日の8時UTC) に実行
    - cron: '0 8 * * *'
  
  # 手動でも実行できるようにする
  workflow_dispatch:

# 実行する処理内容
jobs:
  tweet:
    # 実行環境を指定
    runs-on: ubuntu-latest

    # 処理のステップ
    steps:
      # 1. リポジトリのコードをチェックアウト（お決まりの作業）
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Pythonの環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy pytz

      # 4. Pythonスクリプトを実行して投稿
      - name: Run post tweet script
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: python post_bot.py
